language: python
python:
    - "2.7"
before_install:
    - deactivate
#    - sudo apt-get update -qq
#    - sudo apt-get install -qq python-scipy python-matplotlib python-nose
    - virtualenv --system-site-packages ~/virtualenv/this
    - source ~/virtualenv/this/bin/activate
    - pip install numpy==1.9.2
    - pip install -r requirements.txt
install:
#    - python setup.py build_ext --inplace
    - python setup.py install
script:
    - nosetests

#language: python
#python:
#  - "2.7"
#  - "nightly"
# command to install dependencies
#install: "pip install -r requirements.txt"
# command to run tests
#script: nosetests
